# =============================================
# Google Cloud Build Configuration
# Sri Lanka Repo Ops - CI/CD Pipeline
# =============================================

steps:
  # Step 1: Build the Docker image
  # Environment variables are now in app/env.production.txt (copied to .env.production in Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:latest'
      - '.'
    id: 'build'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA']
    id: 'push-sha'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/srilanka-repo-app:latest']
    id: 'push-latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'srilanka-repo-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/srilanka-repo-app:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'
