# =============================================
# Google Cloud Build Configuration
# Sri Lanka Repo Ops - CI/CD Pipeline
# =============================================

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - './app/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - './app'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'srilanka-repo-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/srilanka-repo-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/srilanka-repo-app:latest'

# Substitution variables (set these in Cloud Build trigger or via command line)
substitutions:
  _REGION: 'asia-south1'  # Mumbai - closest to Sri Lanka
  _NEXT_PUBLIC_SUPABASE_URL: ''
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: ''

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'

